// Code generated by vfsgen; DO NOT EDIT.

// +build !cavemandev

package regionadmin

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	pathpkg "path"
	"time"
)

// EmbeddedAssets statically implements the virtual filesystem provided to vfsgen.
var EmbeddedAssets = func() http.FileSystem {
	mustUnmarshalTextTime := func(text string) time.Time {
		var t time.Time
		err := t.UnmarshalText([]byte(text))
		if err != nil {
			panic(err)
		}
		return t
	}

	fs := vfsgen۰FS{
		"/": &vfsgen۰DirInfo{
			name:    "/",
			modTime: mustUnmarshalTextTime("2018-05-17T17:36:43Z"),
		},
		"/views": &vfsgen۰DirInfo{
			name:    "views",
			modTime: mustUnmarshalTextTime("2018-05-17T10:56:02Z"),
		},
		"/views/admin": &vfsgen۰DirInfo{
			name:    "admin",
			modTime: mustUnmarshalTextTime("2018-05-17T10:56:10Z"),
		},
		"/views/admin/region": &vfsgen۰DirInfo{
			name:    "region",
			modTime: mustUnmarshalTextTime("2018-05-17T10:56:18Z"),
		},
		"/views/admin/region/index.gohtml": &vfsgen۰FileInfo{
			name:    "index.gohtml",
			modTime: mustUnmarshalTextTime("2018-05-17T10:56:50Z"),
			content: []byte("\x2d\x2d\x2d\x0a\x0a\x2d\x2d\x2d\x0a\x7b\x7b\x74\x65\x6d\x70\x6c\x61\x74\x65\x20\x22\x2f\x61\x64\x6d\x69\x6e\x2d\x70\x61\x67\x65\x2e\x67\x6f\x68\x74\x6d\x6c\x22\x20\x2e\x7d\x7d\x0a\x0a\x7b\x7b\x64\x65\x66\x69\x6e\x65\x20\x22\x62\x6f\x64\x79\x22\x7d\x7d\x0a\x0a\x54\x68\x69\x73\x20\x69\x73\x20\x74\x68\x65\x20\x62\x6f\x64\x79\x0a\x0a\x7b\x7b\x65\x6e\x64\x7d\x7d\x0a"),
		},
	}
	fs["/"].(*vfsgen۰DirInfo).entries = []os.FileInfo{
		fs["/views"].(os.FileInfo),
	}
	fs["/views"].(*vfsgen۰DirInfo).entries = []os.FileInfo{
		fs["/views/admin"].(os.FileInfo),
	}
	fs["/views/admin"].(*vfsgen۰DirInfo).entries = []os.FileInfo{
		fs["/views/admin/region"].(os.FileInfo),
	}
	fs["/views/admin/region"].(*vfsgen۰DirInfo).entries = []os.FileInfo{
		fs["/views/admin/region/index.gohtml"].(os.FileInfo),
	}

	return fs
}()

type vfsgen۰FS map[string]interface{}

func (fs vfsgen۰FS) Open(path string) (http.File, error) {
	path = pathpkg.Clean("/" + path)
	f, ok := fs[path]
	if !ok {
		return nil, &os.PathError{Op: "open", Path: path, Err: os.ErrNotExist}
	}

	switch f := f.(type) {
	case *vfsgen۰FileInfo:
		return &vfsgen۰File{
			vfsgen۰FileInfo: f,
			Reader:          bytes.NewReader(f.content),
		}, nil
	case *vfsgen۰DirInfo:
		return &vfsgen۰Dir{
			vfsgen۰DirInfo: f,
		}, nil
	default:
		// This should never happen because we generate only the above types.
		panic(fmt.Sprintf("unexpected type %T", f))
	}
}

// We already imported "compress/gzip" and "io/ioutil", but ended up not using them. Avoid unused import error.
var _ = gzip.Reader{}
var _ = ioutil.Discard

// vfsgen۰FileInfo is a static definition of an uncompressed file (because it's not worth gzip compressing).
type vfsgen۰FileInfo struct {
	name    string
	modTime time.Time
	content []byte
}

func (f *vfsgen۰FileInfo) Readdir(count int) ([]os.FileInfo, error) {
	return nil, fmt.Errorf("cannot Readdir from file %s", f.name)
}
func (f *vfsgen۰FileInfo) Stat() (os.FileInfo, error) { return f, nil }

func (f *vfsgen۰FileInfo) NotWorthGzipCompressing() {}

func (f *vfsgen۰FileInfo) Name() string       { return f.name }
func (f *vfsgen۰FileInfo) Size() int64        { return int64(len(f.content)) }
func (f *vfsgen۰FileInfo) Mode() os.FileMode  { return 0444 }
func (f *vfsgen۰FileInfo) ModTime() time.Time { return f.modTime }
func (f *vfsgen۰FileInfo) IsDir() bool        { return false }
func (f *vfsgen۰FileInfo) Sys() interface{}   { return nil }

// vfsgen۰File is an opened file instance.
type vfsgen۰File struct {
	*vfsgen۰FileInfo
	*bytes.Reader
}

func (f *vfsgen۰File) Close() error {
	return nil
}

// vfsgen۰DirInfo is a static definition of a directory.
type vfsgen۰DirInfo struct {
	name    string
	modTime time.Time
	entries []os.FileInfo
}

func (d *vfsgen۰DirInfo) Read([]byte) (int, error) {
	return 0, fmt.Errorf("cannot Read from directory %s", d.name)
}
func (d *vfsgen۰DirInfo) Close() error               { return nil }
func (d *vfsgen۰DirInfo) Stat() (os.FileInfo, error) { return d, nil }

func (d *vfsgen۰DirInfo) Name() string       { return d.name }
func (d *vfsgen۰DirInfo) Size() int64        { return 0 }
func (d *vfsgen۰DirInfo) Mode() os.FileMode  { return 0755 | os.ModeDir }
func (d *vfsgen۰DirInfo) ModTime() time.Time { return d.modTime }
func (d *vfsgen۰DirInfo) IsDir() bool        { return true }
func (d *vfsgen۰DirInfo) Sys() interface{}   { return nil }

// vfsgen۰Dir is an opened dir instance.
type vfsgen۰Dir struct {
	*vfsgen۰DirInfo
	pos int // Position within entries for Seek and Readdir.
}

func (d *vfsgen۰Dir) Seek(offset int64, whence int) (int64, error) {
	if offset == 0 && whence == io.SeekStart {
		d.pos = 0
		return 0, nil
	}
	return 0, fmt.Errorf("unsupported Seek in directory %s", d.name)
}

func (d *vfsgen۰Dir) Readdir(count int) ([]os.FileInfo, error) {
	if d.pos >= len(d.entries) && count > 0 {
		return nil, io.EOF
	}
	if count <= 0 || count > len(d.entries)-d.pos {
		count = len(d.entries) - d.pos
	}
	e := d.entries[d.pos : d.pos+count]
	d.pos += count
	return e, nil
}
