// Code generated by "stringer -type=DataType -output=data-types_string.go"; DO NOT EDIT.

package ddl

import "strconv"

const _DataType_name = "InvalidCustomVarCharPKBigIntAutoPKVarCharFKBigIntFKIntIntUBigIntBigIntUDoubleDateTimeVarCharBoolTextBlob"

var _DataType_index = [...]uint8{0, 7, 13, 22, 34, 43, 51, 54, 58, 64, 71, 77, 85, 92, 96, 100, 104}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
